title: Your awesome title
author: Owen
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This learning course is awesome

# social links
twitter_username: Opps, I don't use a twitter
github_username:  owenboy007
show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
